server:
  port: 8081

spring:
  application:
    name: aiservice
  profiles:
    active: local
    include:
      - redis
      - eureka
#  config:
#    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

logback:
  log-path: ./logs

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

