spring:
  application:
    name: ai-service
  profiles:
    group:
      "local": "local, gemini, default-datasource, default-db-management, default-redis, eureka, openfeign, actuator"
      "docker": "docker, gemini, default-datasource, default-db-management, default-redis, eureka, openfeign, actuator"
      "prod": "prod, gemini, prod-datasource, prod-db-management, prod-data-redis, eureka, openfeign, actuator"
      active: "PROFILE_ACTIVE"

    config:
      import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

logback:
  log-path: ./logs

